config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :projects
  resources :courses
  root 'welcome#index'

  resources :students do 
     member do  
      get :personal_details 
     end 

    #  another form
    #  get :personal_details  on: :member

     collection do 
        get :activity
     end

    #  another form
    #  get :activity  on: :collection
  end

  namespace :admin do 
    resources :students
  end


  # scope module: :admin do 
  #   resources :students
  # end

  get 'welcome/about'
  get 'about', to: 'welcome#about'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments , as: :commentable
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :student
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :commentable, polymorphic: true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :name, :description, presence: true
    has_and_belongs_to_many :students
end

app/models/demo.rb
class Demo < ApplicationRecord
    has_one :sub_demo

    before_create :greeting_message 

    def greeting_message 
        puts "Hey i will run before you create an object "
    end

    # or you can write as this way 
    # before_create  do 
    #     puts "second meee"
    # end
end

app/models/department.rb
class Department < ApplicationRecord
    has_one :manager
    has_one :manager_history , through: :manager
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :comments, as: :commentable
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :department
  has_one :manager_history
end

app/models/manager_history.rb
class ManagerHistory < ApplicationRecord
  belongs_to :manager
end

app/models/news.rb
class News < ApplicationRecord
    has_many :comments, as: :commentable
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :student_projects 
    has_many :students, through: :student_projects
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :blogs
    validates :first_name, :last_name, :email, presence: true
    validates :email, uniqueness: true
    validates :first_name, :last_name, length: {minimum:10, maximum:50}
    validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\Z/, message: "only letters are allowed"}
    # validates :age, presence: true, numericality: true
    # this check if the value is number 
    
    # custome validation 
    validate :validate_student_age 




    has_and_belongs_to_many :courses
    has_many :student_projects
    has_many :projects, through: :student_projects
    after_save :display_student_age 

    def display_student_age
        if self.date_of_birth.present? 
            age = Date.today.year - date_of_birth.year
            puts "=======age of the student is #{age}"
        else 
            puts "======age cannot be calculated=========="
        end
    end

    def validate_student_age
        if self.date_of_birth.present?
            age = Date.today.year - self.date_of_birth.year
            if age < 15
                errors.add(:age, "please provide valid date of birth, age should be greater than 15")
            end
        end
    end

    def full_name 
        "#{first_name} #{last_name}"
    end

    def age 
        if date_of_birth.present? 
            Date.today.year - date_of_birth.year 
        else 
            nil
        end
    end
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/sub_demo.rb
class SubDemo < ApplicationRecord
  belongs_to :demo
end

app/controllers/admin/students_controller.rb
class Admin::StudentController < ApplicationController 
    # student controller
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    # @blogs = Blog.eager_load(:student).references(:student).where("students.first_name =?", "Bhaleraoghasfh" )
    @blogs = Blog.eager_load(:student)
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.fetch(:blog, {})
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :set_student, only: [:edit, :update, :show, :destroy]
    helper_method :formatted_date
    def index 
        @students = Student.all
    end

    def new 
        @student = Student.new
    end

    def create 
        # @student = Student.create(
        #     first_name: params[:student][:first_name],
        #     last_name: params[:student][:last_name],
        #     email: params[:student][:email],
        # )
        @student = Student.create(student_params)
        @student.save
        if @student.save
            puts "\n\n student saved successfully\n "
            redirect_to students_path
        else  
            render :new
        end
    end

    def show 
    end

    def edit 
    end

    def update 
        if @student.update(student_params)
            redirect_to students_path 
        else 
            render :edit
        end
    end

    def destroy 
        @student.destroy
        redirect_to students_path 
    end

    private
    def student_params 
        params.require(:student).permit(:first_name, :last_name,:email,:date_of_birth,:local_address,:permenant_address,:permanent_contact_number,:alternate_contact_number)
    end

    def set_student 
        @student = Student.find(params[:id])
    end

    def formatted_date(date)
        date.strftime('%A, %b, %d,%Y') if date.present? 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # def formatted_date(date)
    #     date.strftime('%A, %b, %d,%Y') if date.present? 
    # end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/students/_form.html.erb
<%= form_with model: @student do |form| %>
    <% if @student.errors.any? %>
        <% @student.errors.full_messages.each do |msg| %>
            <h3><%= msg%></h3>
        <% end %>
    <% end %>
    <div>
        <%= form.label :first_name %>
        <%= form.text_field :first_name %>
    </div>
    <br>
     <div>
        <%= form.label :last_name %>
        <%= form.text_field :last_name %>
    </div>
    <br>
     <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>
    <br>
     <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>
   
    <br>
     <div>
        <%= form.label :local_address %>
        <%= form.text_field :local_address %>
    </div>
    <br>
     <div>
        <%= form.label :permenant_address %>
        <%= form.text_field :permenant_address %>
    </div>
    <br>
     <div>
        <%= form.label :permanent_contact_number %>
        <%= form.text_field :permanent_contact_number %>
    </div>
    <br>
     <div>
        <%= form.label :alternate_contact_number %>
        <%= form.text_field :alternate_contact_number %>
    </div>
    <br>
    <div>
     <%= form.submit %>
    </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit students </h1>


<%= render "form", student: @student%>

app/views/students/index.html.erb
<h1>Listing all students </h1>
<%= link_to 'Add New Student', new_student_path %>
<table>
    <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Date of Birth</th>
        <th>Local address</th>
        <th>Permanent Address</th>
        <th>Permanent Contact Number</th>
        <th>Alternate Contact Number</th>
        <th colspan=3>Action</th>
    </thead>
    <tbody>
    <% @students.each do |student|%>
        <tr>
            <td><%= student.first_name%></td>
            <td><%= student.last_name%></td>
            <td><%= student.email%></td>
            <td><%= student.date_of_birth%></td>
            <td><%= student.local_address%></td>
            <td><%= student.permenant_address%></td>
            <td><%= student.permanent_contact_number%></td>
            <td><%= student.alternate_contact_number%></td>
            <td><%= link_to 'View', student %></td>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= button_to 'Delete', student_path(student), method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/students/new.html.erb
<h1>New students </h1>

<%= render "form", student: @student%>

app/views/students/show.html.erb
<h1>Student details</h1>
<Strong>Full name: </strong><%= @student.full_name %><br>
<Strong>First Name: </strong><%= @student.first_name %><br>
<Strong>Last Name: </strong><%= @student.last_name %><br>
<Strong>Email: </strong><%= @student.email %><br>
<Strong>Date Of Birth: </strong><%= formatted_date(@student.date_of_birth) %><br>
<Strong>Age: </strong><%= @student.age  %><br>
<Strong>Local Address: </strong><%= @student.local_address %><br>
<Strong>Permanent Address: </strong><%= @student.permenant_address %><br>
<Strong>Permanent Contact Number: </strong><%= @student.permanent_contact_number %><br>
<Strong>Alternate Address: </strong><%= @student.alternate_contact_number %><br>


<%= link_to 'Back', students_path %> | <%= link_to 'Edit', edit_student_path(@student) %>